/**
 * Color Theme Configuration
 *
 * Full palettes per theme: accent colors + light/dark mode backgrounds,
 * sections, cards, header, footer. Each theme is a cohesive color story.
 */

export interface ThemePalette {
  background: string;
  foreground: string;
  card: string;
  cardHover: string;
  border: string;
  borderLight: string;
  muted: string;
  mutedForeground: string;
  sectionAlt: string;
  headerBg: string;
  footerBg: string;
}

export interface ColorTheme {
  id: string;
  name: string;
  emoji: string;
  primary: {
    base: string;
    hover: string;
    light: string;
    ultraLight: string;
    dark: string;
  };
  secondary: {
    base: string;
    hover: string;
    light: string;
  };
  light: ThemePalette;
  dark: ThemePalette;
}

export const colorThemes: ColorTheme[] = [
  {
    id: "rose-garden",
    name: "Rose Garden",
    emoji: "🌹",
    primary: {
      base: "#e11d48",
      hover: "#be123c",
      light: "#fecdd3",
      ultraLight: "#fff1f2",
      dark: "#9f1239",
    },
    secondary: { base: "#f97316", hover: "#ea580c", light: "#fed7aa" },
    light: {
      background: "#fdf2f4",
      foreground: "#1f0f14",
      card: "#ffffff",
      cardHover: "#fff1f3",
      border: "#f5c6d0",
      borderLight: "#fce7eb",
      muted: "#9f4d63",
      mutedForeground: "#c99aa8",
      sectionAlt: "#fce7eb",
      headerBg: "#ffffff",
      footerBg: "#fce7eb",
    },
    dark: {
      background: "#1a0a0f",
      foreground: "#fce7eb",
      card: "#251019",
      cardHover: "#351524",
      border: "#4a2030",
      borderLight: "#2d1419",
      muted: "#d4a5b5",
      mutedForeground: "#9f4d63",
      sectionAlt: "#2d1419",
      headerBg: "#1f0f14",
      footerBg: "#2d1419",
    },
  },
  {
    id: "ocean-depths",
    name: "Ocean Depths",
    emoji: "🌊",
    primary: {
      base: "#0ea5e9",
      hover: "#0284c7",
      light: "#bae6fd",
      ultraLight: "#f0f9ff",
      dark: "#0369a1",
    },
    secondary: { base: "#06b6d4", hover: "#0891b2", light: "#a5f3fc" },
    light: {
      background: "#f0f9ff",
      foreground: "#0c1929",
      card: "#ffffff",
      cardHover: "#e0f2fe",
      border: "#bae6fd",
      borderLight: "#e0f2fe",
      muted: "#0369a1",
      mutedForeground: "#38bdf8",
      sectionAlt: "#e0f2fe",
      headerBg: "#ffffff",
      footerBg: "#e0f2fe",
    },
    dark: {
      background: "#0c1929",
      foreground: "#e0f2fe",
      card: "#0f2744",
      cardHover: "#132f4c",
      border: "#1e3a5f",
      borderLight: "#132f4c",
      muted: "#7dd3fc",
      mutedForeground: "#0ea5e9",
      sectionAlt: "#132f4c",
      headerBg: "#0f172a",
      footerBg: "#132f4c",
    },
  },
  {
    id: "forest-canopy",
    name: "Forest Canopy",
    emoji: "🌲",
    primary: {
      base: "#10b981",
      hover: "#059669",
      light: "#a7f3d0",
      ultraLight: "#ecfdf5",
      dark: "#047857",
    },
    secondary: { base: "#22c55e", hover: "#16a34a", light: "#bbf7d0" },
    light: {
      background: "#f0fdf4",
      foreground: "#0d1f12",
      card: "#ffffff",
      cardHover: "#dcfce7",
      border: "#bbf7d0",
      borderLight: "#dcfce7",
      muted: "#047857",
      mutedForeground: "#34d399",
      sectionAlt: "#dcfce7",
      headerBg: "#ffffff",
      footerBg: "#dcfce7",
    },
    dark: {
      background: "#0d1f12",
      foreground: "#dcfce7",
      card: "#14532d",
      cardHover: "#166534",
      border: "#15803d",
      borderLight: "#14532d",
      muted: "#6ee7b7",
      mutedForeground: "#10b981",
      sectionAlt: "#14532d",
      headerBg: "#0f2917",
      footerBg: "#14532d",
    },
  },
  {
    id: "sunset-blaze",
    name: "Sunset Blaze",
    emoji: "🌅",
    primary: {
      base: "#f59e0b",
      hover: "#d97706",
      light: "#fde68a",
      ultraLight: "#fffbeb",
      dark: "#b45309",
    },
    secondary: { base: "#ef4444", hover: "#dc2626", light: "#fecaca" },
    light: {
      background: "#fffbeb",
      foreground: "#1c1912",
      card: "#ffffff",
      cardHover: "#fef3c7",
      border: "#fde68a",
      borderLight: "#fef3c7",
      muted: "#b45309",
      mutedForeground: "#f59e0b",
      sectionAlt: "#fef3c7",
      headerBg: "#ffffff",
      footerBg: "#fef3c7",
    },
    dark: {
      background: "#1c1410",
      foreground: "#fef3c7",
      card: "#29201a",
      cardHover: "#3d2e24",
      border: "#5c4033",
      borderLight: "#29201a",
      muted: "#fcd34d",
      mutedForeground: "#f59e0b",
      sectionAlt: "#29201a",
      headerBg: "#231a14",
      footerBg: "#29201a",
    },
  },
  {
    id: "violet-dreams",
    name: "Violet Dreams",
    emoji: "💜",
    primary: {
      base: "#8b5cf6",
      hover: "#7c3aed",
      light: "#ddd6fe",
      ultraLight: "#f5f3ff",
      dark: "#6d28d9",
    },
    secondary: { base: "#a855f7", hover: "#9333ea", light: "#e9d5ff" },
    light: {
      background: "#f5f3ff",
      foreground: "#1e1b2e",
      card: "#ffffff",
      cardHover: "#ede9fe",
      border: "#ddd6fe",
      borderLight: "#ede9fe",
      muted: "#6d28d9",
      mutedForeground: "#a78bfa",
      sectionAlt: "#ede9fe",
      headerBg: "#ffffff",
      footerBg: "#ede9fe",
    },
    dark: {
      background: "#15121f",
      foreground: "#ede9fe",
      card: "#1e1b2e",
      cardHover: "#2d2640",
      border: "#3d3552",
      borderLight: "#1e1b2e",
      muted: "#c4b5fd",
      mutedForeground: "#8b5cf6",
      sectionAlt: "#1e1b2e",
      headerBg: "#18151f",
      footerBg: "#1e1b2e",
    },
  },
  {
    id: "midnight-indigo",
    name: "Midnight Indigo",
    emoji: "🌙",
    primary: {
      base: "#6366f1",
      hover: "#4f46e5",
      light: "#c7d2fe",
      ultraLight: "#eef2ff",
      dark: "#4338ca",
    },
    secondary: { base: "#818cf8", hover: "#6366f1", light: "#e0e7ff" },
    light: {
      background: "#eef2ff",
      foreground: "#1e1e3f",
      card: "#ffffff",
      cardHover: "#e0e7ff",
      border: "#c7d2fe",
      borderLight: "#e0e7ff",
      muted: "#4338ca",
      mutedForeground: "#818cf8",
      sectionAlt: "#e0e7ff",
      headerBg: "#ffffff",
      footerBg: "#e0e7ff",
    },
    dark: {
      background: "#0f0f1e",
      foreground: "#e0e7ff",
      card: "#1a1a35",
      cardHover: "#25254d",
      border: "#3730a3",
      borderLight: "#1a1a35",
      muted: "#a5b4fc",
      mutedForeground: "#6366f1",
      sectionAlt: "#1a1a35",
      headerBg: "#141428",
      footerBg: "#1a1a35",
    },
  },
  {
    id: "cherry-blossom",
    name: "Cherry Blossom",
    emoji: "🌸",
    primary: {
      base: "#ec4899",
      hover: "#db2777",
      light: "#fbcfe8",
      ultraLight: "#fdf2f8",
      dark: "#be185d",
    },
    secondary: { base: "#f472b6", hover: "#ec4899", light: "#fce7f3" },
    light: {
      background: "#fdf2f8",
      foreground: "#1f1218",
      card: "#ffffff",
      cardHover: "#fce7f3",
      border: "#fbcfe8",
      borderLight: "#fce7f3",
      muted: "#be185d",
      mutedForeground: "#f472b6",
      sectionAlt: "#fce7f3",
      headerBg: "#ffffff",
      footerBg: "#fce7f3",
    },
    dark: {
      background: "#1a0f14",
      foreground: "#fce7f3",
      card: "#2d1820",
      cardHover: "#3d202c",
      border: "#5c2d3d",
      borderLight: "#2d1820",
      muted: "#f9a8d4",
      mutedForeground: "#ec4899",
      sectionAlt: "#2d1820",
      headerBg: "#1f1218",
      footerBg: "#2d1820",
    },
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    emoji: "✨",
    primary: {
      base: "#eab308",
      hover: "#ca8a04",
      light: "#fef08a",
      ultraLight: "#fefce8",
      dark: "#a16207",
    },
    secondary: { base: "#fbbf24", hover: "#f59e0b", light: "#fef3c7" },
    light: {
      background: "#fefce8",
      foreground: "#1c1912",
      card: "#ffffff",
      cardHover: "#fef9c3",
      border: "#fef08a",
      borderLight: "#fef9c3",
      muted: "#a16207",
      mutedForeground: "#eab308",
      sectionAlt: "#fef9c3",
      headerBg: "#ffffff",
      footerBg: "#fef9c3",
    },
    dark: {
      background: "#1c1810",
      foreground: "#fef9c3",
      card: "#292419",
      cardHover: "#3d3526",
      border: "#5c4d33",
      borderLight: "#292419",
      muted: "#fde047",
      mutedForeground: "#eab308",
      sectionAlt: "#292419",
      headerBg: "#211d14",
      footerBg: "#292419",
    },
  },
  {
    id: "northern-lights",
    name: "Northern Lights",
    emoji: "🌌",
    primary: {
      base: "#14b8a6",
      hover: "#0d9488",
      light: "#99f6e4",
      ultraLight: "#f0fdfa",
      dark: "#0f766e",
    },
    secondary: { base: "#2dd4bf", hover: "#14b8a6", light: "#ccfbf1" },
    light: {
      background: "#f0fdfa",
      foreground: "#0f1f1c",
      card: "#ffffff",
      cardHover: "#ccfbf1",
      border: "#99f6e4",
      borderLight: "#ccfbf1",
      muted: "#0f766e",
      mutedForeground: "#2dd4bf",
      sectionAlt: "#ccfbf1",
      headerBg: "#ffffff",
      footerBg: "#ccfbf1",
    },
    dark: {
      background: "#0d1f1c",
      foreground: "#ccfbf1",
      card: "#134e4a",
      cardHover: "#115e59",
      border: "#0f766e",
      borderLight: "#134e4a",
      muted: "#5eead4",
      mutedForeground: "#14b8a6",
      sectionAlt: "#134e4a",
      headerBg: "#0f2421",
      footerBg: "#134e4a",
    },
  },
  {
    id: "crimson-empire",
    name: "Crimson Empire",
    emoji: "👑",
    primary: {
      base: "#dc2626",
      hover: "#b91c1c",
      light: "#fecaca",
      ultraLight: "#fef2f2",
      dark: "#991b1b",
    },
    secondary: { base: "#7f1d1d", hover: "#991b1b", light: "#fca5a5" },
    light: {
      background: "#fef2f2",
      foreground: "#1c0f0f",
      card: "#ffffff",
      cardHover: "#fee2e2",
      border: "#fecaca",
      borderLight: "#fee2e2",
      muted: "#991b1b",
      mutedForeground: "#f87171",
      sectionAlt: "#fee2e2",
      headerBg: "#ffffff",
      footerBg: "#fee2e2",
    },
    dark: {
      background: "#1a0a0a",
      foreground: "#fee2e2",
      card: "#2d1515",
      cardHover: "#451a1a",
      border: "#7f1d1d",
      borderLight: "#2d1515",
      muted: "#fca5a5",
      mutedForeground: "#dc2626",
      sectionAlt: "#2d1515",
      headerBg: "#1f0f0f",
      footerBg: "#2d1515",
    },
  },
  {
    id: "sage-serenity",
    name: "Sage Serenity",
    emoji: "🍃",
    primary: {
      base: "#84cc16",
      hover: "#65a30d",
      light: "#d9f99d",
      ultraLight: "#f7fee7",
      dark: "#4d7c0f",
    },
    secondary: { base: "#a3e635", hover: "#84cc16", light: "#ecfccb" },
    light: {
      background: "#f7fee7",
      foreground: "#1a1f0f",
      card: "#ffffff",
      cardHover: "#ecfccb",
      border: "#d9f99d",
      borderLight: "#ecfccb",
      muted: "#4d7c0f",
      mutedForeground: "#84cc16",
      sectionAlt: "#ecfccb",
      headerBg: "#ffffff",
      footerBg: "#ecfccb",
    },
    dark: {
      background: "#131a0d",
      foreground: "#ecfccb",
      card: "#1e2e10",
      cardHover: "#365314",
      border: "#4d7c0f",
      borderLight: "#1e2e10",
      muted: "#bef264",
      mutedForeground: "#84cc16",
      sectionAlt: "#1e2e10",
      headerBg: "#161f0f",
      footerBg: "#1e2e10",
    },
  },
  {
    id: "cotton-candy",
    name: "Cotton Candy",
    emoji: "🍬",
    primary: {
      base: "#f472b6",
      hover: "#ec4899",
      light: "#fce7f3",
      ultraLight: "#fdf2f8",
      dark: "#db2777",
    },
    secondary: { base: "#38bdf8", hover: "#0ea5e9", light: "#bae6fd" },
    light: {
      background: "#fdf2f8",
      foreground: "#1e1520",
      card: "#ffffff",
      cardHover: "#fce7f3",
      border: "#fbcfe8",
      borderLight: "#fce7f3",
      muted: "#db2777",
      mutedForeground: "#f472b6",
      sectionAlt: "#eff6ff",
      headerBg: "#ffffff",
      footerBg: "#fce7f3",
    },
    dark: {
      background: "#1a141e",
      foreground: "#fce7f3",
      card: "#2d2035",
      cardHover: "#3d2a48",
      border: "#5c3d6b",
      borderLight: "#2d2035",
      muted: "#f9a8d4",
      mutedForeground: "#f472b6",
      sectionAlt: "#1e2742",
      headerBg: "#1f1824",
      footerBg: "#2d2035",
    },
  },
];

export const defaultColorTheme = colorThemes.find((t) => t.id === "sunset-blaze") ?? colorThemes[0];

export function getColorThemeById(id: string): ColorTheme {
  return colorThemes.find((t) => t.id === id) ?? defaultColorTheme;
}
